name: wo_form
description: "A package made for easily creating forms, with Womotaq's identity."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_atomic_design:
    path: ../package_atomic_design

dependency_overrides:
  package_atomic_design:
    path: ../package_atomic_design

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
